server:
  port: 9527

spring:
  application:
    name: GATEWAY-SERVIVCE
  cloud:
    gateway:
      routes:
        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/order/create/**
        - id: stock_route
          uri: lb://stock-service
          predicates: 
            - Path=/stock/intercept/**
            - After=2021-03-21T13:51:01.558+08:00[Asia/Shanghai]
      discovery:
        locator:
          #表示gateway开启服务注册和发现功能,
          #并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          #表示将请求路径的服务名配置改成小写  因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8900/eureka/,http://eureka2:8901/eureka/,http://eureka3:8902/eureka/
    fetch-registry: true
  instance:
    #将ip地址注册到Eureka注册中心
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  